name: cicd
on:
  push:
  workflow_dispatch:

jobs:
### PREPARE ###
  cp:
    name: cp
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: cp --help
    - run: |
        mkdir "./dist"
        cp -r "./test" "./dist/test"
        ls -l "./dist"
        ls -l "./dist/test"        
    - run: |
        mkdir "./dist/test2"
        cp -rv "./dist/test/*" "./dist/test2/"
        ls -l "./dist"
        ls -l "./dist/test2"                

