name: cicd
on:
  push:
  workflow_dispatch:

jobs:
### PREPARE ###
  cp:
    name: cp
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: cp --help
    - run: |
        mkdir "./dist"
        cp -a "test/." "dist"
        ls -l "./dist"

