name: cicd
on:
  push:
  workflow_dispatch:

jobs:
### PREPARE ###
  cp:
    name: cp
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: |
        mkdir "./dist"
        mkdir "./dist/core"
        cp -r "./test" "./dist/core"
    - run: |
        ls -l "./dist"
        ls -l "./dist/core"
        cp -R "./dist/core/*" "./dist/customer/"
        ls -l "./dist"

