name: cicd
on:
  push:
  workflow_dispatch:

jobs:
### PREPARE ###
  cp:
    name: cp
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: cp --help
    - run: |
        mkdir "./dist"
        cp -r "test/." "dist"
        ls -l "./dist"

  test:
    name: test
    runs-on: windows-latest
    steps:
      - run: echo "$env:LOCALAPPDATA"
      - run: echo "electron-builder=$env:LOCALAPPDATA\electron-builder\Cache"
